model_user:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  time_life_token: 2
avt:
  default_size: 80
  size: 50
  resize_limit_width: 500
  resize_limit_height: 500
  size_img: 5
page:
  per_page: 10
micropost:
  maximum: 140
img:
  accept: "image/jpeg,image/gif,image/png"
  size_img: 5
